language: go
sudo: false
go:
 - 1.6.2
before_install:
 - wget -O go_appengine_sdk_linux_amd64.zip https://sdkversion.appspot.com/
 - unzip -d $HOME go_appengine_sdk_linux_amd64.zip
 - export PATH=$PATH:$HOME/go_appengine
 - goapp get -v github.com/mattn/goveralls
 - goapp get -v golang.org/x/tools/cmd/cover
install:
 - goapp get -v -t -d github.com/qedus/appengine/...
script:
 - ./test.sh
after_success:
 - goveralls -coverprofile=coverage.txt -service=travis-ci
